baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'HugoAgent'

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

[params]
  github_repo = 'https://github.com/Priii07/HugoAgent'
  github_branch = 'main'
  
  # Logo and branding
  navbar_logo = true
  navbar_translucent_over_cover_disable = false
  
  # Enable Lunr.js offline search
  offlineSearch = true
  
  # Enable syntax highlighting
  prism_syntax_highlighting = true

[params.ui]
  # Set to true to disable breadcrumb navigation.
  breadcrumb_disable = false
  # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
  sidebar_search_disable = false
  # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
  navbar_logo = true
  # Set to true to disable the About link in the site footer
  footer_about_disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Navigation
[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
